# Dockerfile.test
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents
COPY . /app

# Install dependencies including test libraries
RUN pip install --no-cache-dir -r requirements.txt

# Run pytest by default
CMD ["pytest"]
